# Generated by Django 3.1.7 on 2021-03-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(error_messages={'null': 'Este campo no puede estar vacio'}, help_text='Nombre que aparecerá en el curriculum', max_length=200)),
                ('position', models.CharField(error_messages={'max_length': 'Has excedido la cantidad de letras disponible', 'null': 'Este campo no puede estar vacio'}, help_text='Tu puesto actual', max_length=100)),
                ('description', models.CharField(blank=True, error_messages={'max_length': 'Tiene que ser una descripción corta de 300 carácteres'}, help_text='Breve descripción de ti', max_length=300, null=True)),
                ('birthdate', models.DateTimeField(error_messages={'null': 'Este campo no puede estar vacio'}, help_text='Tu fecha de nacimiento')),
                ('address', models.CharField(blank=True, error_messages={'max_length': 'Tiene que ser menor de 300 carácteres'}, help_text='(Opcional) Tu dirección', max_length=300, null=True)),
                ('phone_number', models.IntegerField(error_messages={'null': 'Necesitas un número donde te contacten'}, help_text='Máx. 15 dígitos')),
                ('email', models.EmailField(error_messages={'max_length': 'Has excedido el numero disponible de dígitos', 'null': 'Necesitas un correro donde te contacten'}, max_length=100)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Procura que sea sólo una palabra... corta', 'null': 'No puedes dejar a tu habilidad sin nombre'}, max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculums.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(error_messages={'null': 'No puedes dejar este campo vacío'}, help_text='El nombre de la empresa donde trabajaste', max_length=50)),
                ('position', models.CharField(error_messages={'null': 'No puedes dejar este campo vacío'}, help_text='El cargo que desarrollaste', max_length=50)),
                ('beggining_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(auto_now=True, help_text='Por favor define esta fecha de lo contrario será la actual y se tomara como trabajo actual')),
                ('description', models.CharField(error_messages={'null': 'No puedes dejar este campo vacío'}, help_text='Una breve descripción de lo que hiciste', max_length=100)),
                ('insight_type', models.CharField(choices=[('Experience', 'experience'), ('Education', 'education')], max_length=30)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculums.curriculum')),
            ],
        ),
    ]
