# Generated by Django 3.1.7 on 2021-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='birthdate',
            field=models.DateField(error_messages={'null': 'Este campo no puede estar vacio'}, help_text='Tu fecha de nacimiento'),
        ),
    ]
