# Generated by Django 3.1.7 on 2021-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0002_auto_20210303_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='phone_number',
            field=models.CharField(error_messages={'null': 'Necesitas un número donde te contacten'}, help_text='Máx. 15 dígitos', max_length=15),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
