# Generated by Django 3.1.7 on 2021-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0004_auto_20210303_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='beggining_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insight',
            name='end_date',
            field=models.DateField(auto_now=True, help_text='Por favor define esta fecha de lo contrario será la actual y se tomara como trabajo actual'),
        ),
    ]
