# Generated by Django 3.1.7 on 2021-03-03 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0005_auto_20210303_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, help_text='Por favor define esta fecha de lo contrario será la actual y se tomara como trabajo actual'),
        ),
    ]
